
# PostgreSQL database URL
spring.datasource.url=jdbc:postgresql://localhost:5432/MaintenenceTechDB

# PostgreSQL username
spring.datasource.username=postgres

# PostgreSQL password
spring.datasource.password=4321


# =========================================================
# JPA / Hibernate Configuration
# =========================================================

# Hibernate will create/update database tables
# automatically when we add our Entity classes.
spring.jpa.hibernate.ddl-auto=update

# Show SQL queries in the console.
# This helps us understand what Hibernate is doing.
spring.jpa.show-sql=true

# Make SQL output easier to read.
spring.jpa.properties.hibernate.format_sql=true